### ISSUE TITLE
Feature request: Timer

### ISSUE THREAD

**Issue by JelleGraaf** [b0tting/escapemachine#2]
Can you build a button in the web interface, which starts a timer (MM:SS)? Preferably with an adjustable end time (let's say: I want it to stop, buzz, or play an MP3 at 15 minutes).
Bonus points are for logging the state changes to the time of the timer at that time :).

**Comment by b0tting** [comment]
I've added a timer that also includes a log of state changes with timestamps. 

What is an "adjustable end time"? Can you give me an example?

**Comment by JelleGraaf** [comment]
I'd like the timer to stop or flash or do something when the predetermined time ends. In this very example: if my players aren't out of the room in 15 minutes, they lost and I end the game.

**Comment by b0tting** [comment]
Timer changes color, logs an event and attempts to vibrate the browser client (not supported on iOS, sadly)
