### ISSUE TITLE
Switch to seperate sound and music channels

### ISSUE THREAD

**Issue by b0tting** [b0tting/escapemachine#3]
We need to switch to separate sound and music channels:
- in the config file, configure three background music tracks
- play the first when getting to 1/2 of the time, the second when getting to 4/5 of the time and the final music track
- when playing hints or sound effects, lower volume of the music until the effect is done

**Comment by JelleGraaf** [comment]
Small edit: start playing the sound from the start. The track will be of the right length. Start a different track when the bathroom state triggers and a final one for when endgame triggers.

**Comment by b0tting** [comment]
Added a configureable sound track for the three stages of the game. Music will lower volume when hints are being playing. Music will stop when "standby" state is selected.
