### ISSUE TITLE
Output pins are off

### ISSUE THREAD

**Issue by JelleGraaf** [b0tting/escapemachine#4]
The Output pins (lamp, spot, magnet) don't correspond to what the web interface states. Next to that, the web interface doesn't allow for manual switching anymore. When you toggle one of the three buttons, the output doesn't change and the switch toggles back to its original state.
A small table (Lamp (L), Spot (S), Magnet (M) of results for what the Web Interface says (and should be the right state) and what the true output is (which is incorrect).
State Entree: 
Web Interface: Lon/Soff/Mon, Output: Loff/Son/Moff
State Badkamer: Loff/Son/Moff. Output: Lon/Soff/Mon
State Eindspel: Lon/Soff/Moff. Output: Loff/Son/Mon

Can you fixe these two issues?

**Comment by b0tting** [comment]
I need your hand in testing..

**Comment by JelleGraaf** [comment]
These have been fixed, thanks
