### ISSUE TITLE
Output pins are back to XIO, please use CSID again

### ISSUE THREAD

**Issue by JelleGraaf** [b0tting/escapemachine#5]
Originally, we used XIO pins for output. LAter on, we decided that CSID's were more suited because of their greater power capacity. Can you change the code of escape.conf to the following again:
[Escape]
sounddir = ./static/sounds
volume = 85
logfile = ./escape.log
debug = False
bookbutton1pin = XIO-P2
bookbutton2pin = XIO-P4
keybuttonpin = XIO-P6
lamppin = CSID1
spotpin = CSID3
magnetpin = CSID5
bathroomeffect = vic.mp3

**Comment by b0tting** [comment]
I've changed the config file to escape.conf.example, so your file will not be overwritten any longer.
