### ISSUE TITLE
Interface change requests

### ISSUE THREAD

**Issue by JelleGraaf** [b0tting/escapemachine#9]
1) Can you place the clock somewhere where it's always visible (the tabs below that, we do love the tabs).
2) Can you create some space between the Shutdown/Reboot buttons and the tabs? We use iPad and iPhone for control and when browsing through the tabs, they are a little too close for comfort.
3) Can you swap the System and Hints tabs?

**Comment by b0tting** [comment]
All done. I'm not satisfied with the clock, please give some feedback on that.
